<a href="https://colab.research.google.com/github/svetlanama/ai_practice/blob/dev/final_svitlana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модулів

In [4]:
import pandas as pd

Дані про діабет

In [14]:
# Load the CSV from Google Drive
url = 'https://drive.google.com/uc?id=1lMc8CKRE3Txuk4ntqpVpzM1qTlQkYADd'
data = pd.read_csv(url)

# Display the first few rows
data.head()

# columns = df.columns.delete(-1)
# data = df[columns]
# df[columns] = (data - data.min()) / (data.max() - data.min())

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import re

# data.iloc[0,3]

# Function to extract skills from job descriptions
# def extract_skills(description):
#     skills_keywords = [
#         'Python', 'SQL', 'Excel', 'Machine Learning', 'Tableau', 'Power BI',
#         'R', 'Java', 'C++', 'TensorFlow', 'Pandas', 'Numpy', 'MATLAB', 'SAS',
#         'Data Analysis', 'Deep Learning', 'Cloud', 'AWS', 'Azure', 'JavaScript', 'React'
#     ]
#     skills = []
#     for skill in skills_keywords:
#         escaped_skill = re.escape(skill)
#         if re.search(rf'\b{escaped_skill}\b', description, re.IGNORECASE):
#             skills.append(skill)
#     return ', '.join(skills)

# # # Extract skills from the Job Description column
# # extract_skills(data.iloc[0,3])
# data['Extracted Skills'] = data['Job Description'].apply(extract_skills)

# data
# Preprocess features
# vectorizer = TfidfVectorizer(max_features=1000)
# X_skills = vectorizer.fit_transform(data['Skills Required'])





# Extract skills and convert them into binary columns
def extract_skills_binary(description, skills_keywords):
    # Create a dictionary to hold binary values for each skill
    skill_presence = {skill: 0 for skill in skills_keywords}
    for skill in skills_keywords:
        escaped_skill = re.escape(skill)
        if re.search(rf'\b{escaped_skill}\b', description, re.IGNORECASE):
            skill_presence[skill] = 1
    return skill_presence

# Define skill keywords
# TODO: add more skills
skills_keywords = [
    'Python', 'SQL', 'Excel', 'Machine Learning', 'Tableau', 'Power BI',
    'R', 'Java', 'C++', 'TensorFlow', 'Pandas', 'Numpy', 'MATLAB', 'SAS',
    'Data Analysis', 'Deep Learning', 'Cloud', 'AWS', 'Azure', 'JavaScript', 'React'
]

# Apply the skill extraction function to each job description
skills_binary = data['Job Description'].apply(lambda desc: extract_skills_binary(desc, skills_keywords))

# Convert the list of dictionaries into a DataFrame
skills_df = pd.DataFrame(list(skills_binary))

# skills_df

# Concatenate the original DataFrame with the skills binary DataFrame
data_with_skills = pd.concat([data, skills_df], axis=1)

data_with_skills

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Numpy,MATLAB,SAS,Data Analysis,Deep Learning,Cloud,AWS,Azure,JavaScript,React
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,...,0,1,1,1,0,0,0,0,0,0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,...,0,0,0,0,0,0,0,0,0,0
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,...,0,0,1,1,0,0,0,0,0,0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,...,0,0,0,1,1,0,0,0,0,0
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,...,0,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,...,0,0,0,1,0,1,1,0,0,0
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,...,0,0,0,0,0,0,0,0,0,0
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,...,0,0,0,0,0,0,0,0,0,0
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,...,0,0,0,0,0,1,0,0,1,0
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,...,0,0,0,0,0,0,0,0,0,1

Потрібно на основі інформації пацієнта виявити наявність діабету `Outcome`

# Завдання 1
Створіть клас Dataset для тренувальних та тестових даних

In [38]:
# Define a function to calculate 'Fit' based on user skills
# TODO: think more about calculating fit: take into
# - account amount of skill years
# - amount of total experience
# - how many techology exists
def calculate_fit(row, user_skills_binary, threshold=0.5):
    # Count the number of matching skills
    matching_skills = sum([row[skill] == 1 and user_skills_binary[skill] == 1 for skill in skills_keywords])
    total_skills_required = sum([1 for skill in skills_keywords if row[skill] == 1])

    # Calculate the percentage of matching skills
    if total_skills_required == 0:
        return 0  # If no skills are required, we consider it not a fit
    match_percentage = matching_skills / total_skills_required
    return 1 if match_percentage >= threshold else 0

# Function to predict fit based on user input
def predict_job_fit(user_skills, model, skills_keywords, data_with_skills):
    # Convert user skills to binary features
    user_skills_binary = {skill: 0 for skill in skills_keywords}
    for skill in user_skills:
        if skill in skills_keywords:
            user_skills_binary[skill] = 1

    # Apply the 'calculate_fit' function to each job in the dataset
    data_with_skills['Fit'] = data_with_skills.apply(lambda row: calculate_fit(row, user_skills_binary), axis=1)

    # Now you can use the trained model to predict the fit (optional, based on 'Fit' column)
    X = data_with_skills[skills_keywords]  # Using the skill columns as features
    y = data_with_skills['Fit']  # Fit column shows if user fit for the proper position

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, y_pred))

# Example user skills
user_skills = ['Python', 'C++', 'Excel', 'Data Analysis']

# Create a model (can be RandomForestClassifier or any other)
# TODO: have more experiments
model = RandomForestClassifier(random_state=42)

# Train the model and calculate fit
# TODO: move training to separate step (not to mixup)
predict_job_fit(user_skills, model, skills_keywords, data_with_skills)

# Display the DataFrame with the 'Fit' column
data_with_skills[['Job Title', 'Job Description', 'Fit']].head()


# TODO: instead 1 or 0 provide percent, learn model and later ask for new user and new job

Accuracy: 0.96875

,Job Title,Job Description,Fit
0,Data Scientist,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",0
1,Healthcare Data Scientist,What You Will Do:\n\nI. General Summary\n\nThe...,0
2,Data Scientist,"KnowBe4, Inc. is a high growth information sec...",0
3,Data Scientist,*Organization and Job ID**\nJob ID: 310709\n\n...,1
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,0

# Завдання 2
Створіть DataLoader

# Завдання 3
Створіть нейромережу

# Завдання 4
Визначте функцію втрат та оптимізатор

# Завдання 5
Натренуйте нейромережу. Візміть невелику кількість епох

In [ ]:
# @title Функція для тренування
import time

def train(model, optimizer, loss_fn, train_dl, val_dl,
          metrics=None, metrics_name=None, epochs=20, device='cpu', task='regression'):
    '''
    Runs training loop for classification problems. Returns Keras-style
    per-epoch history of loss and accuracy over training and validation data.

    Parameters
    ----------
    model : nn.Module
        Neural network model
    optimizer : torch.optim.Optimizer
        Search space optimizer (e.g. Adam)
    loss_fn :
        Loss function (e.g. nn.CrossEntropyLoss())
    train_dl :
        Iterable dataloader for training data.
    val_dl :
        Iterable dataloader for validation data.
    metrics: list
        List of sklearn metrics functions to be calculated
    metrics_name: list
        List of matrics names
    epochs : int
        Number of epochs to run
    device : string
        Specifies 'cuda' or 'cpu'
    task : string
        type of problem. It can be regression, binary or multiclass

    Returns
    -------
    Dictionary
        Similar to Keras' fit(), the output dictionary contains per-epoch
        history of training loss, training accuracy, validation loss, and
        validation accuracy.
    '''

    print('train() called: model=%s, opt=%s(lr=%f), epochs=%d, device=%s\n' % \
          (type(model).__name__, type(optimizer).__name__,
           optimizer.param_groups[0]['lr'], epochs, device))

    metrics = metrics if metrics else []
    metrics_name = metrics_name if metrics_name else [metric.__name__ for metric in metrics]

    history = {} # Collects per-epoch loss and metrics like Keras' fit().
    history['loss'] = []
    history['val_loss'] = []
    for name in metrics_name:
        history[name] = []
        history[f'val_{name}'] = []

    start_time_train = time.time()

    for epoch in range(epochs):

        # --- TRAIN AND EVALUATE ON TRAINING SET -----------------------------
        start_time_epoch = time.time()

        model.train()
        history_train = {name: 0 for name in ['loss']+metrics_name}

        for batch in train_dl:
            x    = batch[0].to(device)
            y    = batch[1].to(device)
            y_pred = model(x)
            loss = loss_fn(y_pred, y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            y_pred = y_pred.detach().cpu().numpy()
            y = y.detach().cpu().numpy()


            history_train['loss'] += loss.item() * x.size(0)
            for name, func in zip(metrics_name, metrics):
              try:
                  history_train[name] += func(y, y_pred) * x.size(0)
              except:
                  if task == 'binary': y_pred_ = y_pred.round()
                  elif task == 'multiclass': y_pred_ = y_pred.argmax(axis=-1)
                  history_train[name] += func(y, y_pred_) * x.size(0)

        for name in history_train:
            history_train[name] /= len(train_dl.dataset)


        # --- EVALUATE ON VALIDATION SET -------------------------------------
        model.eval()
        history_val = {'val_' + name: 0 for name in metrics_name+['loss']}

        with torch.no_grad():
            for batch in val_dl:
                x    = batch[0].to(device)
                y    = batch[1].to(device)
                y_pred = model(x)
                loss = loss_fn(y_pred, y)

                y_pred = y_pred.cpu().numpy()
                y = y.cpu().numpy()

                history_val['val_loss'] += loss.item() * x.size(0)
                for name, func in zip(metrics_name, metrics):
                    try:
                        history_val['val_'+name] += func(y, y_pred) * x.size(0)
                    except:
                        if task == 'binary': y_pred_ = y_pred.round()
                        elif task == 'multiclass': y_pred_ = y_pred.argmax(axis=-1)

                        history_val['val_'+name] += func(y, y_pred_) * x.size(0)

        for name in history_val:
            history_val[name] /= len(val_dl.dataset)

        # PRINTING RESULTS

        end_time_epoch = time.time()

        for name in history_train:
            history[name].append(history_train[name])
            history['val_'+name].append(history_val['val_'+name])

        total_time_epoch = end_time_epoch - start_time_epoch

        print(f'Epoch {epoch+1:4d} {total_time_epoch:4.0f}sec', end='\t')
        for name in history_train:
            print(f'{name}: {history[name][-1]:10.3g}', end='\t')
            print(f"val_{name}: {history['val_'+name][-1]:10.3g}", end='\t')
        print()

    # END OF TRAINING LOOP

    end_time_train       = time.time()
    total_time_train     = end_time_train - start_time_train
    print()
    print('Time total:     %5.2f sec' % (total_time_train))

    return history

# Завдання 6
Збережіть нейромережу та зробіть прогноз