<a href="https://colab.research.google.com/github/svetlanama/ai_practice/blob/dev/final_svitlana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модулів

In [71]:
import pandas as pd

# Load the CSV from Google Drive
url = 'https://drive.google.com/uc?id=1lMc8CKRE3Txuk4ntqpVpzM1qTlQkYADd'
data = pd.read_csv(url)

# Display the first few rows
data.head()

# columns = df.columns.delete(-1)
# data = df[columns]
# df[columns] = (data - data.min()) / (data.max() - data.min())

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [72]:
def extract_skills(description):
    skills = ['Python', 'Machine Learning', 'SQL', 'Data Analysis', 'TensorFlow', 'Pandas']  # Define a skill list
    found_skills = [skill for skill in skills if skill.lower() in description.lower()]
    return found_skills

data['Skills'] = data['Job Description'].apply(extract_skills)
data

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Skills
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,"[Python, Machine Learning, Data Analysis]"
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,"[Python, Machine Learning]"
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,"[Python, Machine Learning, SQL, Data Analysis]"
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...","[Python, Machine Learning, Data Analysis]"
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee","[Python, Machine Learning, SQL]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini","[Python, Machine Learning, SQL, Data Analysis]"
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1,[Machine Learning]
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,[Machine Learning]
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),Slalom,"[Python, SQL]"
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1,"[Python, Machine Learning]"

In [74]:
import re

def process_salary_range(salary_range):
    if salary_range.strip() == '-1' or salary_range.strip() == '-1.0':
        return 0, 0

    # Remove non-numeric characters except '-' for ranges
    salary_range = re.sub(r'[^\d\-\s]', '', salary_range)  # Remove $, K, and text
    # Split into low and high ranges
    low, high = salary_range.split('-')
    # Convert 'K' to thousands
    low = int(low.strip()) * 1000
    high = int(high.strip()) * 1000
    return low, high

# Example usage
example_salary = "$95K-$160K (Glassdoor est.)"
min_salary, max_salary = process_salary_range(example_salary)
print(f"Min Salary: {min_salary}, Max Salary: {max_salary}")


# Now filter out rows where Salary Estimate is -1 or NaN
# data = data[~data['Salary Estimate'].isin(['-1', '-1.0'])]


# Check the cleaned data
# data

# # # Apply the function to each row in the 'Salary Estimate' column
def process_salary_with_debug(salary_range):
    # print(f"Processing Salary Range: {salary_range}")  # Debug print
    return process_salary_range(salary_range)  # Call the actual function

# # # Apply the debugging function
for _, row in data.iterrows():
    low, high = process_salary_with_debug(row['Salary Estimate'])
    data[['Min Salary', 'Max Salary']] = low, high


data



# data
# data[['Min Salary', 'Max Salary']] = data['Salary Estimate'].apply(
#     lambda x: pd.Series(process_salary_with_debug(x))
# )

# data[['Min Salary', 'Max Salary']] = data['Salary Estimate'].apply(
#     lambda x: pd.Series(process_salary_range(x))
# )

# # Check the updated DataFrame
# data.head()

Min Salary: 95000, Max Salary: 160000

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Skills,Min Salary,Max Salary
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,"[Python, Machine Learning, Data Analysis]",61000,126000
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,"[Python, Machine Learning]",61000,126000
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,"[Python, Machine Learning, SQL, Data Analysis]",61000,126000
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...","[Python, Machine Learning, Data Analysis]",61000,126000
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee","[Python, Machine Learning, SQL]",61000,126000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini","[Python, Machine Learning, SQL, Data Analysis]",61000,126000
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1,[Machine Learning],61000,126000
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,[Machine Learning],61000,126000
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),Slalom,"[Python, SQL]",61000,126000
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1,"[Python, Machine Learning]",61000,126000

In [75]:
for skill in ['Python', 'Machine Learning', 'SQL', 'Data Analysis', 'TensorFlow', 'Pandas']:
    data[skill] = data['Skills'].apply(lambda x: 1 if skill in x else 0)

data

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Competitors,Skills,Min Salary,Max Salary,Python,Machine Learning,SQL,Data Analysis,TensorFlow,Pandas
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,...,-1,"[Python, Machine Learning, Data Analysis]",61000,126000,1,1,0,1,0,0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,...,-1,"[Python, Machine Learning]",61000,126000,1,1,0,0,0,0
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,...,-1,"[Python, Machine Learning, SQL, Data Analysis]",61000,126000,1,1,1,1,0,0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,...,"Oak Ridge National Laboratory, National Renewa...","[Python, Machine Learning, Data Analysis]",61000,126000,1,1,0,1,0,0
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,...,"Commerce Signals, Cardlytics, Yodlee","[Python, Machine Learning, SQL]",61000,126000,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,...,"See Tickets, TicketWeb, Vendini","[Python, Machine Learning, SQL, Data Analysis]",61000,126000,1,1,1,1,0,0
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,...,-1,[Machine Learning],61000,126000,0,1,0,0,0,0
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,...,-1,[Machine Learning],61000,126000,0,1,0,0,0,0
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,...,Slalom,"[Python, SQL]",61000,126000,1,0,1,0,0,0
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,...,-1,"[Python, Machine Learning]",61000,126000,1,1,0,0,0,0

In [77]:
# Prepare the input (X) and output (y) as follows:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# Define features (binary skill columns) and target (Salary Estimate)
X = data[['Python', 'Machine Learning', 'SQL', 'Data Analysis', 'TensorFlow', 'Pandas']]
# y = data['Salary Estimate']  # Ensure this is numeric (convert if necessary)
y = data[['Min Salary', 'Max Salary']]
# X = X.astype(float)

# Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Split the data # train and test
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

X_train
X_test
y_train
y_test

     Min Salary  Max Salary
342       61000      126000
864       61000      126000
522       61000      126000
544       61000      126000
682       61000      126000
..          ...         ...
549       61000      126000
33        61000      126000
31        61000      126000
713       61000      126000
433       61000      126000

[192 rows x 2 columns]

In [135]:
# Step 2: Train the Neural Network

# Now use X_train and y_train to train the model:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

print(f'>>>>model>>>>>')
X_train.shape[1]
# Define the model TODO: experiment more
# model = Sequential([
#     Dense(64, input_dim=X_train.shape[1], activation='relu'),  # Input layer
#     Dense(32, activation='relu'),  # Hidden layer
#     Dense(1)  # Output layer for regression
# ])
model = Sequential([
     Dense(64, input_dim=X_train.shape[1], activation='relu'),  # Input layer
    # Dense(64, input_dim=10, activation='relu', name="dense_21"),
    Dense(32, activation='relu', name="dense_22"),
    Dense(1, name="dense_23")  # Output layer
])
# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

# Evaluate the model on test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

print(f'>>>>model>>>>>')
model.layers

>>>>model>>>>>
Epoch 1/100

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 9798474752.0000 - mae: 93499.8672 - val_loss: 9798392832.0000 - val_mae: 93499.4219
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9798337536.0000 - mae: 93499.1250 - val_loss: 9798206464.0000 - val_mae: 93498.4219
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9798095872.0000 - mae: 93497.8438 - val_loss: 9797849088.0000 - val_mae: 93496.5312
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9797633024.0000 - mae: 93495.3594 - val_loss: 9797188608.0000 - val_mae: 93492.9766
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9796777984.0000 - mae: 93490.7969 - val_loss: 9796024320.0000 - val_mae: 93486.7578
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9795376128.0000 - mae: 93483.2891 - val_loss: 9794096128.0000 - val_mae: 93476.4375
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9793053696.0000 - mae: 93470.8672 - val_loss: 9791151104.0000 - val_mae: 93460.6953
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9789303808.0000 - mae: 93450.8047 - val_loss: 9786956800.0000 - val_mae: 93438.2500
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9784148992.0000 - mae: 93423.2109 - val_loss: 9781328896.0000 - val_mae: 93408.1172
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9777904640.0000 - mae: 93389.7891 - val_loss: 9773971456.0000 - val_mae: 93368.7188
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9769495552.0000 - mae: 93344.7344 - val_loss: 9764738048.0000 - val_mae: 93319.2422
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9759157248.0000 - mae: 93289.3203 - val_loss: 9753337856.0000 - val_mae: 93258.1016
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9745580032.0000 - mae: 93216.4922 - val_loss: 9739781120.0000 - val_mae: 93185.3359
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9730264064.0000 - mae: 93134.2266 - val_loss: 9723545600.0000 - val_mae: 93098.1016
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9710106624.0000 - mae: 93025.8438 - val_loss: 9704947712.0000 - val_mae: 92998.0391
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9689643008.0000 - mae: 92915.6719 - val_loss: 9683513344.0000 - val_mae: 92882.5625
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9666586624.0000 - mae: 92791.3281 - val_loss: 9659143168.0000 - val_mae: 92751.0469
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9638533120.0000 - mae: 92639.7031 - val_loss: 9631839232.0000 - val_mae: 92603.4141
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9615601664.0000 - mae: 92515.5234 - val_loss: 9601372160.0000 - val_mae: 92438.3359
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9577783296.0000 - mae: 92310.4375 - val_loss: 9567149056.0000 - val_mae: 92252.4609
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9533687808.0000 - mae: 92070.6875 - val_loss: 9529331712.0000 - val_mae: 92046.5234
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9494862848.0000 - mae: 91858.6484 - val_loss: 9487968256.0000 - val_mae: 91820.6016
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9449576448.0000 - mae: 91610.7969 - val_loss: 9442134016.0000 - val_mae: 91569.4531
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9398088704.0000 - mae: 91328.1562 - val_loss: 9392955392.0000 - val_mae: 91298.9922
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9336072192.0000 - mae: 90986.2656 - val_loss: 9339266048.0000 - val_mae: 91002.5781
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9266939904.0000 - mae: 90603.6641 - val_loss: 9282342912.0000 - val_mae: 90686.9766
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9216827392.0000 - mae: 90323.5859 - val_loss: 9222421504.0000 - val_mae: 90353.2578
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9158088704.0000 - mae: 89994.7031 - val_loss: 9159146496.0000 - val_mae: 89999.1953
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9082464256.0000 - mae: 89569.8516 - val_loss: 9091288064.0000 - val_mae: 89617.5000
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9022712832.0000 - mae: 89232.6094 - val_loss: 9019284480.0000 - val_mae: 89210.2422
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8935769088.0000 - mae: 88740.2656 - val_loss: 8942284800.0000 - val_mae: 88772.1016
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8862164992.0000 - mae: 88318.6094 - val_loss: 8862146560.0000 - val_mae: 88313.1406
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8746330112.0000 - mae: 87650.9375 - val_loss: 8777485312.0000 - val_mae: 87824.9922
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8628667392.0000 - mae: 86970.5469 - val_loss: 8689623040.0000 - val_mae: 87314.6953
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8588177408.0000 - mae: 86726.0234 - val_loss: 8598537216.0000 - val_mae: 86781.7031
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8412303360.0000 - mae: 85696.6094 - val_loss: 8502322176.0000 - val_mae: 86214.0391
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8346508288.0000 - mae: 85296.0547 - val_loss: 8403464704.0000 - val_mae: 85625.8594
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8267892224.0000 - mae: 84820.3828 - val_loss: 8301624320.0000 - val_mae: 85014.5000
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8153692672.0000 - mae: 84137.0625 - val_loss: 8193994240.0000 - val_mae: 84362.0625
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8019339776.0000 - mae: 83310.6797 - val_loss: 8082666496.0000 - val_mae: 83680.2891
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7895587840.0000 - mae: 82545.1016 - val_loss: 7970544640.0000 - val_mae: 82986.5312
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7770297856.0000 - mae: 81753.8359 - val_loss: 7854163456.0000 - val_mae: 82258.3359
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7647340032.0000 - mae: 80979.3594 - val_loss: 7734992384.0000 - val_mae: 81503.9766
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7501553152.0000 - mae: 80051.0781 - val_loss: 7614838784.0000 - val_mae: 80734.2891
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7449816576.0000 - mae: 79685.4141 - val_loss: 7492222976.0000 - val_mae: 79938.8281
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7229558272.0000 - mae: 78279.2031 - val_loss: 7366820352.0000 - val_mae: 79114.5312
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7116279808.0000 - mae: 77482.2578 - val_loss: 7241393152.0000 - val_mae: 78278.8516
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6988487680.0000 - mae: 76622.2266 - val_loss: 7112844800.0000 - val_mae: 77409.9766
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6857819648.0000 - mae: 75707.4141 - val_loss: 6980878848.0000 - val_mae: 76504.1875
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6726981120.0000 - mae: 74767.5156 - val_loss: 6847134720.0000 - val_mae: 75571.4766
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6537283072.0000 - mae: 73462.3906 - val_loss: 6713327104.0000 - val_mae: 74623.1094
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6472340480.0000 - mae: 72934.2188 - val_loss: 6581742592.0000 - val_mae: 73674.9219
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6294429184.0000 - mae: 71643.2969 - val_loss: 6446226944.0000 - val_mae: 72680.5938
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6107117056.0000 - mae: 70228.7422 - val_loss: 6310886400.0000 - val_mae: 71669.2188
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5980888064.0000 - mae: 69267.7188 - val_loss: 6177846784.0000 - val_mae: 70656.3828
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5779161600.0000 - mae: 67635.4297 - val_loss: 6041809920.0000 - val_mae: 69599.0859
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5613886976.0000 - mae: 66341.7812 - val_loss: 5909221376.0000 - val_mae: 68547.9844
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5615059456.0000 - mae: 66313.2031 - val_loss: 5777076224.0000 - val_mae: 67478.3359
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5448162816.0000 - mae: 64973.3828 - val_loss: 5645526528.0000 - val_mae: 66390.0234
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5291060736.0000 - mae: 63631.7812 - val_loss: 5514211840.0000 - val_mae: 65297.3984
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5221690368.0000 - mae: 62896.7383 - val_loss: 5385619968.0000 - val_mae: 64250.5156
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5037191168.0000 - mae: 61400.6211 - val_loss: 5258361856.0000 - val_mae: 63199.5703
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4954768384.0000 - mae: 60645.6797 - val_loss: 5133923840.0000 - val_mae: 62145.9922
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4684449280.0000 - mae: 58401.4648 - val_loss: 5010756608.0000 - val_mae: 61105.9414
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4629736448.0000 - mae: 58004.5898 - val_loss: 4890553344.0000 - val_mae: 60116.3516
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4603420160.0000 - mae: 57800.3438 - val_loss: 4773581312.0000 - val_mae: 59158.4688
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4509008896.0000 - mae: 56869.7070 - val_loss: 4659315712.0000 - val_mae: 58216.9414
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4348809216.0000 - mae: 55526.4648 - val_loss: 4548959744.0000 - val_mae: 57281.1445
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4088419328.0000 - mae: 53314.2930 - val_loss: 4442187264.0000 - val_mae: 56347.9609
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4073802496.0000 - mae: 53287.4727 - val_loss: 4338155008.0000 - val_mae: 55410.1836
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3852864768.0000 - mae: 51112.0469 - val_loss: 4236929280.0000 - val_mae: 54650.7891
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3830809600.0000 - mae: 51130.7539 - val_loss: 4140946176.0000 - val_mae: 53953.2812
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3629586432.0000 - mae: 49668.6367 - val_loss: 4046850048.0000 - val_mae: 53277.7070
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3668175616.0000 - mae: 50164.0820 - val_loss: 3957492992.0000 - val_mae: 52613.3984
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3590854144.0000 - mae: 49561.1562 - val_loss: 3871705856.0000 - val_mae: 51952.9336
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3445106176.0000 - mae: 48452.5508 - val_loss: 3790045952.0000 - val_mae: 51300.5820
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3414295296.0000 - mae: 48159.1602 - val_loss: 3712450816.0000 - val_mae: 50657.4180
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3299826432.0000 - mae: 47267.1641 - val_loss: 3638217728.0000 - val_mae: 50018.6914
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3335498496.0000 - mae: 47510.7656 - val_loss: 3570401024.0000 - val_mae: 49413.2930
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3047550464.0000 - mae: 45177.3711 - val_loss: 3504719360.0000 - val_mae: 48803.6914
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3145947392.0000 - mae: 45810.4336 - val_loss: 3443094784.0000 - val_mae: 48209.7383
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2992510720.0000 - mae: 44519.5273 - val_loss: 3384409344.0000 - val_mae: 47621.8164
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2914706432.0000 - mae: 43818.3789 - val_loss: 3328399616.0000 - val_mae: 47245.2930
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2998448640.0000 - mae: 44559.6875 - val_loss: 3276806144.0000 - val_mae: 46954.3789
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2792503040.0000 - mae: 42954.0312 - val_loss: 3227471616.0000 - val_mae: 46664.3828
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2861739520.0000 - mae: 43576.2539 - val_loss: 3182323712.0000 - val_mae: 46387.4297
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2822300928.0000 - mae: 43681.3359 - val_loss: 3138833408.0000 - val_mae: 46109.9297
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2822394624.0000 - mae: 43549.0000 - val_loss: 3097488896.0000 - val_mae: 45851.0859
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2668767744.0000 - mae: 42482.0156 - val_loss: 3062043136.0000 - val_mae: 45629.7930
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2707957504.0000 - mae: 42753.3359 - val_loss: 3026427904.0000 - val_mae: 45416.1211
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2647147264.0000 - mae: 42385.7461 - val_loss: 2993530880.0000 - val_mae: 45211.0508
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2672659968.0000 - mae: 42822.9297 - val_loss: 2964690944.0000 - val_mae: 45023.8438
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2677157888.0000 - mae: 42776.4688 - val_loss: 2937344256.0000 - val_mae: 44838.9883
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2599812352.0000 - mae: 42060.2422 - val_loss: 2912317696.0000 - val_mae: 44673.3633
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2628466176.0000 - mae: 42360.7969 - val_loss: 2887887872.0000 - val_mae: 44508.2227
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2603853824.0000 - mae: 42267.2383 - val_loss: 2864472320.0000 - val_mae: 44344.4648
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2452706816.0000 - mae: 41048.3125 - val_loss: 2844134400.0000 - val_mae: 44195.4023
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2526850304.0000 - mae: 41700.3164 - val_loss: 2824420096.0000 - val_mae: 44047.3906
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2520912128.0000 - mae: 41535.3047 - val_loss: 2805219328.0000 - val_mae: 43898.9688
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2557878272.0000 - mae: 41912.0195 - val_loss: 2787265536.0000 - val_mae: 43756.6016
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2364420608.0000 - mae: 40308.1367
Test Loss: 2409766912.0, Test MAE: 40712.78515625
>>>>model>>>>>

[<Dense name=dense_25, built=True>,
 <Dense name=dense_22, built=True>,
 <Dense name=dense_23, built=True>]

In [142]:
from tensorflow.keras.models import Model


# Create a new list of layers without the last layer
new_layers = model.layers[:-1]  # Exclude the last layer

# Build a new model using the new layers
model_output = Sequential(new_layers)
print("Original2 model layers:", new_model.layers)
# Now create a new output model if you want the output of the second-to-last layer
# model_output = Model(inputs=model.input, outputs=new_model.layers[-1].output)



# # Assuming you have a trained model and want to remove the last layer
# print("Original model layers:", model.layers)
# # Remove the last layer
# model.layers.pop()
# print("Original2 model layers:", model.layers)

# model.layers[-1]

# # Create a new model without the last layer
# model_output = Model(inputs=model.input, outputs=model.layers[-1].output)  # Get output from the second-to-last layer

# # Print the number of layers after removal
# print("Number of layers in the model after removal:", len(model.layers))
# print(model.layers)

# Example user skills (binary vector for skills)
# user_skills = np.array([1, 1, 0, 1, 0, 1]).reshape(1, -1)  # Reshape to match input shape

# # Get the features from the modified model (without the last layer)
# features = model_output.predict(user_skills)

# # Print the output features
# # print(f'Features from hidden layer: {features}')
# features

Original2 model layers: [<Dense name=dense_25, built=True>, <Dense name=dense_22, built=True>]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
Features from hidden layer: [[   0.        0.        0.     2209.3958    0.        0.        0.
     0.        0.        0.     2226.3733 2327.6724    0.     2293.6592
  2224.6008 2301.4026 2168.6707 2201.0164 2175.969  2255.128  2283.8364
  2234.5063    0.     2267.316     0.     2176.6863    0.     2202.062
     0.        0.     2207.4543    0.    ]]

array([[   0.    ,    0.    ,    0.    , 2209.3958,    0.    ,    0.    ,
           0.    ,    0.    ,    0.    ,    0.    , 2226.3733, 2327.6724,
           0.    , 2293.6592, 2224.6008, 2301.4026, 2168.6707, 2201.0164,
        2175.969 , 2255.128 , 2283.8364, 2234.5063,    0.    , 2267.316 ,
           0.    , 2176.6863,    0.    , 2202.062 ,    0.    ,    0.    ,
        2207.4543,    0.    ]], dtype=float32)

In [157]:
# user_skills = np.array([1, 1, 0, 1, 0, 1]).reshape(1, -1)  # Reshape to match input shape


import numpy as np

# Let's say the user has the following skills:
# for skill in ['Python', 'Machine Learning', 'SQL', 'Data Analysis', 'TensorFlow', 'Pandas']:
user_skills = np.array([1, 1, 0, 1, 0, 1]).reshape(1, -1)  # Example user skill vector


predicted_fit = model_output.predict(user_skills)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

In [ ]:
 ###### End #######

In [145]:
# 4. Remove the Last Layer
from tensorflow.keras.models import Model
# print(f'>>>>>>>>>')
# model.layers

# model.layers.pop()  # Remove the last layer
# print(f'>>>>>>>>>')
# model.layers
# model_output = Sequential(model.layers)
print("Number of layers in the model:", len(model.layers))
print(model.layers)

model = model.layers.pop
print("Number of layers in the model_output:", model)
model
# model_output = Model(inputs=model.input, outputs=model.layers[-2].output)

Number of layers in the model: 3
[<Dense name=dense_25, built=True>, <Dense name=dense_22, built=True>, <Dense name=dense_23, built=True>]
Number of layers in the model_output: <built-in method pop of list object at 0x7abe75e27f80>

In [132]:
# # Example user skills (binary vector for skills)
# # X = data[['Python', 'Machine Learning', 'SQL', 'Data Analysis', 'TensorFlow', 'Pandas']]
# import numpy as np
# user_skills = np.array([1, 1, 0, 1, 0, 1]).reshape(1, -1)  # Reshape to match input shape

# # Get model_output from the second-to-last layer (hidden layer)
# features = model.predict(user_skills)

# # Print the output features (before the last layer)
# print(f'Features from hidden layer: {features}')


from tensorflow.keras.models import Model
import numpy as np

# Assuming `model` is already trained and compiled

# Example user skills (binary vector for skills)
user_skills = np.array([1, 1, 0, 1, 0, 1]).reshape(1, -1)  # Reshape to match input shape

# Create a model that outputs features from the second-to-last hidden layer
#model_output = Model(inputs=model.input, outputs=model.layers[1].output)  # Second layer

# Get the features from the hidden layer
features = model.predict(user_skills)

# Print the output features (before the last layer)
print(f'Features from hidden layer: {features}')

AttributeError: 'builtin_function_or_method' object has no attribute 'predict'

In [86]:
######################################

In [ ]:
# 3. Train a Neural Network Model for Salary Prediction
# Preprocess the data:

# Convert the Salary Estimate into numeric labels (e.g., mean salary).
# One-hot encode categorical variables (e.g., Industry, Location).
# Normalize the input features.
# Build and train a Neural Network model using TensorFlow/Keras:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the model
model = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

Prepare data

In [7]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Concatenate, Dropout
from sklearn.preprocessing import OneHotEncoder


## Other features
# encoder = OneHotEncoder(sparse=False)
# # Example with encoded features
# encoded_job_title = encoder.fit_transform(data[['job_title']]).toarray()  # Shape (num_jobs, 3)
# encoded_location = encoder.fit_transform(data[['location']]).toarray()  # Shape (num_jobs, 3)
# encoded_education = encoder.fit_transform(data[['education_level']]).toarray()  # Shape (num_jobs, 3)

# # Numerical features
# company_size = data[['company_size']].values  # Shape (num_jobs, 1)
# experience_level = data[['experience_level']].values  # Shape (num_jobs, 1)

# # Concatenate all features
# X_other_features = np.concatenate([
#     encoded_job_title,
#     encoded_location,
#     encoded_education,
#     company_size,
#     experience_level
# ], axis=1)

# Step 1: Prepare Model
skills_keywords = [
    'Python', 'SQL', 'Excel', 'Machine Learning', 'Tableau', 'Power BI',
    'R', 'Java', 'C++', 'TensorFlow', 'Pandas', 'Numpy', 'MATLAB', 'SAS',
    'Data Analysis', 'Deep Learning', 'Cloud', 'AWS', 'Azure', 'JavaScript', 'React'
]

# Create a binary vector based on the predefined skills list
# Vectorise user skills in relation to skills_keywords - mark where is exists
user_skills = ['Python', 'C++', 'Excel']
skills_vector = [1 if skill in user_skills else 0 for skill in skills_keywords]
print("User skill vectorised")
print(skills_vector)

num_skills = len(skills_keywords)
num_features = 0 # TODO: later update with the test above

# Input layers
skills_input = Input(shape=(num_skills,), name='skills_input')  # Binary encoded skills
other_features_input = Input(shape=(num_features,), name='other_features')  # Other job-related features

print("skills_input")
skills_input
print("other_features_input")
other_features_input

# Skill encoding layers
skills_embedding = Dense(128, activation='relu', name='skills_embedding')(skills_input)
skills_embedding = Dropout(0.3)(skills_embedding)

# Combine with other features
combined = Concatenate(name='combined_features')([skills_embedding, other_features_input])
x = Dense(64, activation='relu')(combined)
x = Dropout(0.3)(x)
x = Dense(32, activation='relu')(x)

# Output layer (predict normalized salary)
salary_output = Dense(1, activation='linear', name='salary_output')(x)
print("salary_output")
salary_output

# Define the full model
model = Model(inputs=[skills_input, other_features_input], outputs=salary_output)

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Summary
model.summary()

User skill vectorised
[1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
skills_input
other_features_input
salary_output

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ skills_input (InputLayer) │ (None, 21)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ skills_embedding (Dense)  │ (None, 128)            │          2,816 │ skills_input[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_2 (Dropout)       │ (None, 128)            │              0 │ skills_embedding[0][0] │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ other_features            │ (None, 0)              │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ combined_features         │ (None, 128)            │              0 │ dropout_2[0][0],       │
│ (Concatenate)             │                        │                │ other_features[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_2 (Dense)           │ (None, 64)             │          8,256 │ combined_features[0][… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_3 (Dropout)       │ (None, 64)             │              0 │ dense_2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 32)             │          2,080 │ dropout_3[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ salary_output (Dense)     │ (None, 1)              │             33 │ dense_3[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 13,185 (51.50 KB)

 Trainable params: 13,185 (51.50 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
# from sklearn.preprocessing import StandardScaler, OneHotEncoder

# import numpy as np

# # Example dataset with other features for each job
# other_features = [
#     {'education_level': 'Bachelor', 'experience_level': 3, 'company_size': 500},
#     {'education_level': 'Master', 'experience_level': 5, 'company_size': 2000},
#     {'education_level': 'PhD', 'experience_level': 10, 'company_size': 50}
# ]

# # Convert categorical features (e.g., education_level) to one-hot encoding
# encoder = OneHotEncoder() # sparse=False
# education_encoded = encoder.fit_transform([[d['education_level']] for d in other_features])

# # Combine categorical and numerical features (e.g., experience_level, company_size)
# scaler = StandardScaler()
# experience_company_scaled = scaler.fit_transform([[d['experience_level'], d['company_size']] for d in other_features])

# # Combine all features into a single matrix
# X_other_features = np.hstack([education_encoded, experience_company_scaled])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [13]:
# Preparation X_skills

import numpy as np

skills_keywords = [
    'Python', 'SQL', 'Excel', 'Machine Learning', 'Tableau', 'Power BI',
    'R', 'Java', 'C++', 'TensorFlow', 'Pandas', 'Numpy', 'MATLAB', 'SAS',
    'Data Analysis', 'Deep Learning', 'Cloud', 'AWS', 'Azure', 'JavaScript', 'React'
]

# Function to encode skills for each job or user
def encode_skills(skill_list):
    return [1 if skill in skill_list else 0 for skill in skills_keywords]

# Example: List of skills for each job (you would normally extract this from job descriptions or user data)
job_skills = [
    ['Python', 'SQL', 'Machine Learning'],
    ['Excel', 'Power BI', 'Java'],
    ['Python', 'C++', 'Deep Learning']
]

# Apply encoding to each job's skill list
X_skills = np.array([encode_skills(skills) for skills in job_skills])

X_skills

# X_skills:
# [[1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]  # First job: ['Python', 'SQL', 'Machine Learning']
#  [0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]  # Second job: ['Excel', 'Power BI', 'Java']
#  [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0]] # Third job: ['Python', 'C++', 'Deep Learning']

array([[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [9]:
# Summary of Inputs:
# X_skills: Binary matrix encoding the presence of skills for each job.
# X_other_features: Matrix of numerical and/or encoded categorical features for each job.
# y_salary: Numeric target representing salary.

# Step 3 - Train model:
X_other_features = 0 # TODO: extend with level of expertise, etc..
# X_skills: Binary matrix of skills (shape: num_jobs x num_skills)
y_salary = np.array([75, 100, 120])  # Example salary values in thousands
# Step 2: Train Model
history = model.fit(
    [X_skills, X_other_features],  # Inputs
    y_salary,  # Target: Normalized salary
    batch_size=32,
    epochs=50,
    validation_split=0.2
)

ValueError: Argument `validation_split` is only supported for tensors or NumPy arrays.Found incompatible type in the input: [<class 'int'>]

In [ ]:
# Step 4 - Extract Skill Embeddings:
# Create an encoder model that outputs skill embeddings
encoder_model = Model(inputs=model.input, outputs=model.get_layer('skills_embedding').output)

# Extract skill embeddings for all jobs
skill_embeddings = encoder_model.predict([X_skills, X_other_features])

# Save embeddings to a vector database
# Example: FAISS
import faiss
dimension = skill_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)  # L2 similarity
index.add(skill_embeddings)

In [16]:
# Step 5
#5. Predict Fit for a User:

#Convert the user's skills into the same binary format.
#Use the encoder model to generate an embedding for the user's skills.
#Compare the user's embedding to job embeddings in the vector database using similarity search.


# User's binary skills vector
user_skills_vector = [1, 0, 1, 0, 1, ...]  # Example: User has Python, Excel, no C++

# Generate the user's skill embedding
user_embedding = encoder_model.predict([np.array([user_skills_vector]), np.zeros((1, num_features))])

# Find the closest matches in the vector database
k = 5  # Number of closest matches
distances, indices = index.search(user_embedding, k)

# Print the top job matches
print("Closest jobs:", indices)
print("Distances:", distances)

In [1]:
#from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import re



# Extract skills and convert them into binary columns
def extract_skills_binary(description, skills_keywords):
    # Create a dictionary to hold binary values for each skill
    skill_presence = {skill: 0 for skill in skills_keywords}
    for skill in skills_keywords:
        escaped_skill = re.escape(skill)
        if re.search(rf'\b{escaped_skill}\b', description, re.IGNORECASE):
            skill_presence[skill] = 1
    return skill_presence

# Define skill keywords
# TODO: add more skills
skills_keywords = [
    'Python', 'SQL', 'Excel', 'Machine Learning', 'Tableau', 'Power BI',
    'R', 'Java', 'C++', 'TensorFlow', 'Pandas', 'Numpy', 'MATLAB', 'SAS',
    'Data Analysis', 'Deep Learning', 'Cloud', 'AWS', 'Azure', 'JavaScript', 'React'
]

# Apply the skill extraction function to each job description
skills_binary = data['Job Description'].apply(lambda desc: extract_skills_binary(desc, skills_keywords))

# Convert the list of dictionaries into a DataFrame
skills_df = pd.DataFrame(list(skills_binary))

# skills_df

# Concatenate the original DataFrame with the skills binary DataFrame
data_with_skills = pd.concat([data, skills_df], axis=1)

data_with_skills

NameError: name 'data' is not defined

Потрібно на основі інформації пацієнта виявити наявність діабету `Outcome`

# Exam

In [38]:
# Define a function to calculate 'Fit' based on user skills
# TODO: think more about calculating fit: take into
# - account amount of skill years
# - amount of total experience
# - how many techology exists
def calculate_fit(row, user_skills_binary, threshold=0.5):
    # Count the number of matching skills
    matching_skills = sum([row[skill] == 1 and user_skills_binary[skill] == 1 for skill in skills_keywords])
    total_skills_required = sum([1 for skill in skills_keywords if row[skill] == 1])

    # Calculate the percentage of matching skills
    if total_skills_required == 0:
        return 0  # If no skills are required, we consider it not a fit
    match_percentage = matching_skills / total_skills_required
    return 1 if match_percentage >= threshold else 0

# Function to predict fit based on user input
def predict_job_fit(user_skills, model, skills_keywords, data_with_skills):
    # Convert user skills to binary features
    user_skills_binary = {skill: 0 for skill in skills_keywords}
    for skill in user_skills:
        if skill in skills_keywords:
            user_skills_binary[skill] = 1

    # Apply the 'calculate_fit' function to each job in the dataset
    data_with_skills['Fit'] = data_with_skills.apply(lambda row: calculate_fit(row, user_skills_binary), axis=1)

    # Now you can use the trained model to predict the fit (optional, based on 'Fit' column)
    X = data_with_skills[skills_keywords]  # Using the skill columns as features
    y = data_with_skills['Fit']  # Fit column shows if user fit for the proper position

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, y_pred))

# Example user skills
user_skills = ['Python', 'C++', 'Excel', 'Data Analysis']

# Create a model (can be RandomForestClassifier or any other)
# TODO: have more experiments
model = RandomForestClassifier(random_state=42)

# Train the model and calculate fit
# TODO: move training to separate step (not to mixup)
predict_job_fit(user_skills, model, skills_keywords, data_with_skills)

# Display the DataFrame with the 'Fit' column
data_with_skills[['Job Title', 'Job Description', 'Fit']].head()


# TODO: instead 1 or 0 provide percent, learn model and later ask for new user and new job

Accuracy: 0.96875

,Job Title,Job Description,Fit
0,Data Scientist,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",0
1,Healthcare Data Scientist,What You Will Do:\n\nI. General Summary\n\nThe...,0
2,Data Scientist,"KnowBe4, Inc. is a high growth information sec...",0
3,Data Scientist,*Organization and Job ID**\nJob ID: 310709\n\n...,1
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,0

# Завдання 2
Створіть DataLoader

# Завдання 3
Створіть нейромережу

# Завдання 4
Визначте функцію втрат та оптимізатор

# Завдання 5
Натренуйте нейромережу. Візміть невелику кількість епох

In [ ]:
# @title Функція для тренування
import time

def train(model, optimizer, loss_fn, train_dl, val_dl,
          metrics=None, metrics_name=None, epochs=20, device='cpu', task='regression'):
    '''
    Runs training loop for classification problems. Returns Keras-style
    per-epoch history of loss and accuracy over training and validation data.

    Parameters
    ----------
    model : nn.Module
        Neural network model
    optimizer : torch.optim.Optimizer
        Search space optimizer (e.g. Adam)
    loss_fn :
        Loss function (e.g. nn.CrossEntropyLoss())
    train_dl :
        Iterable dataloader for training data.
    val_dl :
        Iterable dataloader for validation data.
    metrics: list
        List of sklearn metrics functions to be calculated
    metrics_name: list
        List of matrics names
    epochs : int
        Number of epochs to run
    device : string
        Specifies 'cuda' or 'cpu'
    task : string
        type of problem. It can be regression, binary or multiclass

    Returns
    -------
    Dictionary
        Similar to Keras' fit(), the output dictionary contains per-epoch
        history of training loss, training accuracy, validation loss, and
        validation accuracy.
    '''

    print('train() called: model=%s, opt=%s(lr=%f), epochs=%d, device=%s\n' % \
          (type(model).__name__, type(optimizer).__name__,
           optimizer.param_groups[0]['lr'], epochs, device))

    metrics = metrics if metrics else []
    metrics_name = metrics_name if metrics_name else [metric.__name__ for metric in metrics]

    history = {} # Collects per-epoch loss and metrics like Keras' fit().
    history['loss'] = []
    history['val_loss'] = []
    for name in metrics_name:
        history[name] = []
        history[f'val_{name}'] = []

    start_time_train = time.time()

    for epoch in range(epochs):

        # --- TRAIN AND EVALUATE ON TRAINING SET -----------------------------
        start_time_epoch = time.time()

        model.train()
        history_train = {name: 0 for name in ['loss']+metrics_name}

        for batch in train_dl:
            x    = batch[0].to(device)
            y    = batch[1].to(device)
            y_pred = model(x)
            loss = loss_fn(y_pred, y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            y_pred = y_pred.detach().cpu().numpy()
            y = y.detach().cpu().numpy()


            history_train['loss'] += loss.item() * x.size(0)
            for name, func in zip(metrics_name, metrics):
              try:
                  history_train[name] += func(y, y_pred) * x.size(0)
              except:
                  if task == 'binary': y_pred_ = y_pred.round()
                  elif task == 'multiclass': y_pred_ = y_pred.argmax(axis=-1)
                  history_train[name] += func(y, y_pred_) * x.size(0)

        for name in history_train:
            history_train[name] /= len(train_dl.dataset)


        # --- EVALUATE ON VALIDATION SET -------------------------------------
        model.eval()
        history_val = {'val_' + name: 0 for name in metrics_name+['loss']}

        with torch.no_grad():
            for batch in val_dl:
                x    = batch[0].to(device)
                y    = batch[1].to(device)
                y_pred = model(x)
                loss = loss_fn(y_pred, y)

                y_pred = y_pred.cpu().numpy()
                y = y.cpu().numpy()

                history_val['val_loss'] += loss.item() * x.size(0)
                for name, func in zip(metrics_name, metrics):
                    try:
                        history_val['val_'+name] += func(y, y_pred) * x.size(0)
                    except:
                        if task == 'binary': y_pred_ = y_pred.round()
                        elif task == 'multiclass': y_pred_ = y_pred.argmax(axis=-1)

                        history_val['val_'+name] += func(y, y_pred_) * x.size(0)

        for name in history_val:
            history_val[name] /= len(val_dl.dataset)

        # PRINTING RESULTS

        end_time_epoch = time.time()

        for name in history_train:
            history[name].append(history_train[name])
            history['val_'+name].append(history_val['val_'+name])

        total_time_epoch = end_time_epoch - start_time_epoch

        print(f'Epoch {epoch+1:4d} {total_time_epoch:4.0f}sec', end='\t')
        for name in history_train:
            print(f'{name}: {history[name][-1]:10.3g}', end='\t')
            print(f"val_{name}: {history['val_'+name][-1]:10.3g}", end='\t')
        print()

    # END OF TRAINING LOOP

    end_time_train       = time.time()
    total_time_train     = end_time_train - start_time_train
    print()
    print('Time total:     %5.2f sec' % (total_time_train))

    return history

# Завдання 6
Збережіть нейромережу та зробіть прогноз